/*
 * generated by Xtext 2.35.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalDockerConfigParser;
import org.xtext.services.DockerConfigGrammarAccess;

public class DockerConfigParser extends AbstractAntlrParser {

	@Inject
	private DockerConfigGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDockerConfigParser createParser(XtextTokenStream stream) {
		return new InternalDockerConfigParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Service";
	}

	public DockerConfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DockerConfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
