/*
 * generated by Xtext 2.35.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.DockerConfigRuntimeModule;
import org.xtext.DockerConfigStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DockerConfigIdeSetup extends DockerConfigStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DockerConfigRuntimeModule(), new DockerConfigIdeModule()));
	}
	
}
