/*
 * generated by Xtext 2.35.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.dockerconfig.ui.internal.DockerconfigActivator;

public class DockerConfigUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DockerconfigActivator.getInstance().getInjector("org.xtext.DockerConfig");
	}

}
