/*
 * generated by Xtext 2.35.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDockerConfigScopeProvider extends DelegatingScopeProvider {
}
