/*
 * generated by Xtext 2.35.0
 */
package org.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DockerConfigRuntimeModule extends AbstractDockerConfigRuntimeModule {
}
