/*
 * generated by Xtext 2.35.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DockerConfigStandaloneSetup extends DockerConfigStandaloneSetupGenerated {

	public static void doSetup() {
		new DockerConfigStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
