/*
 * generated by Xtext 2.35.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.dockerconfig.ui.internal.DockerconfigActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DockerConfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DockerconfigActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DockerconfigActivator activator = DockerconfigActivator.getInstance();
		return activator != null ? activator.getInjector(DockerconfigActivator.ORG_XTEXT_DOCKERCONFIG) : null;
	}

}
