/*
 * generated by Xtext 2.35.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DockerConfigUiModule extends AbstractDockerConfigUiModule {

	public DockerConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
